# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

#你的头像url
avatar: https://avatars0.githubusercontent.com/u/104366?v=3&u=5fba657b5d0375e25d3b129dc5b316aca1f10145&s=140
